### ISSUE TITLE
Navigation and Routing

### ISSUE THREAD

**Issue by draschke** [6of5/UI5SplitApp-Boilerplate#6]
Hi guys,

the routing features of OpenUI5 have changed strongly with 1.30. 
Is there an intention to bring the boilerplate on the new nice routing features in the near future?

Would be great!
BR,
Dirk

**Comment by 6of5** [comment]
Hi Dirk,

routing is used in the Fiori Edition of UI5BP. It is based on an UIComponent. It is currently running with the latest stable version v1.30.8. See [https://github.com/6of5/UI5-Boilerplate-Fiori](https://github.com/6of5/UI5-Boilerplate-Fiori). Could you request missing features there?

The original UI5 Boilerplate (this repo) will staying as simple as possible, so no routing and no UIComponent.

BR, HP

**Comment by draschke** [comment]
Hi HP, 
I'm still on holidays, but if I'm back, i'll take a deeper look on it. But very glad to know this. 
Thank you for your great work! 
BR, 
Dirk
